### ISSUE TITLE
Copying elements with nested elements of another disicpline fails

### ISSUE THREAD

**Issue by franzTobiasDLR** [virtualsatellite/VirtualSatellite4-Core#26]
When copying elements with nested elements that are owned by another discipline, fails. 

Steps to reproduce:
-Create new project and create an element with a nested element (eg. system with a subsystem)
-Assign the nested element to a different discipline
-Copy the parent element

Observations:
-Operation seemed to have worked at first
-After VirSat restart the nested element cannot be resolved anymore... it shows an unresolvable SEI

Guess:
Copy operation works, but saving the new element uses a command that checks roles... As the nested element is of another discipline, we cannot add it the system.

**Comment by SaMuellerDLR** [comment]
Should be fixed since 4.8.0 due to ticket #609 in the old ticket system.
Copy&pasting of elements for which one did not have any rights, used to be a problem since one doesnt have the right to save them.
Disciplines of pasted objects are now always set to the parent discipline, so this issue should no longe occur. Please verify @franzTobiasDLR

**Comment by franzTobiasDLR** [comment]
The issue still exists in the latest version.
