### ISSUE TITLE
IDE update does not work because some plugions are missing

### ISSUE THREAD

**Issue by franzTobiasDLR** [virtualsatellite/VirtualSatellite4-Core#900]
When trying to update the IDE it's complaining that external.lib.swagger and external.lib.jersy are not found in the repo... DId we miss something here?

**Comment by JAmmermann-DLR** [comment]
@franzTobiasDLR I am having issues with reproducing the error. Yesterday I managed to reproduce it, but today I didn't. Maybe because the IDE from the dev got build again? Can you still reproduce it with the current dev? Maybe we can look into it together then.

P.S.: The only things I found, are resolved in the commit above (but they are still only in this branch...)
